let shopItemsData = [
    {
      id: "itemA",
      name: "Casual Shirt",
      price: 999,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "img-1.jpg",
    },
    {
      id: "itemB",
      name: "Office Shirt",
      price: 1199,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "img-2.jpg",
    },
    {
      id: "itemC",
      name: "T Shirt",
      price: 699,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "img-3.jpg",
    },
    {
      id: "itemD",
      name: "Mens Suit",
      price: 11990,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "img-4.jpg",
    },
    {
      id: "thiecbawdjksadjk",
      name: "Mens Tie",
      price: 2500,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "img-5.png",
    },
    {
      id: "iuertrywebncdjksadjk",
      name: "Casual shoes",
      price: 21999,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "img-6.png",
    },
    {
      id: "thierytbvcbvzdhadjk",
      name: "black suit",
      price: 6999,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "img-7.png",
    },
    {
      id: "trfoiwfcnbcawdjksadjk",
      name: "polo shirt",
      price: 8999,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "img-8.png",
    },
    {
      id: "cbvxbcvsceldk",
      name: "denim shirt",
      price: 8599,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "img-9.png",
    },
    {
      id: "oiopijmjkhuihb",
      name: "denim pants",
      price: 12999,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "img-10.png",
    },
    {
      id: "oiopijewyiohbjhib",
      name: "basic cap",
      price: 3999,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "img-11.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "leather boots",
      price: 79900,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "img-12.png",
    },
  ];